name: bioinfo_r
channels: [conda-forge, bioconda, defaults]
dependencies:
  - r-base
  - r-tidyverse
  - r-ggplot2
  - r-dplyr
  - r-readr
  - r-tidyr
  - r-devtools
  - r-data.table
  - r-irkernel
  - r-phyloseq
  - bioconductor-dada2
  - bioconductor-deseq2
